[package]
name = "conduit-op-reth-rpc-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
alloy-primitives = { workspace = true, features = ["serde"] }
jsonrpsee = { workspace = true, features = ["server", "macros"] }
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
