[package]
name = "conduit-op-reth-rpc-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
alloy-json-rpc.workspace = true
alloy-primitives.workspace = true
jsonrpsee = { workspace = true, features = ["server", "macros"] }
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
