name: Cold Docker Build

on:
  pull_request:
    paths:
      - Dockerfile
      - .dockerignore
      - Cargo.toml
      - Cargo.lock
      - crates/**/Cargo.toml
      - .github/workflows/cold-docker-build.yaml
      - .github/workflows/docker-build.yaml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest-16core
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 16
      - uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          target: conduit-op-reth-build
          build-args: |
            BUILD_PROFILE=maxperf
            FEATURES=asm-keccak,jemalloc,keccak-cache-global,otlp,js-tracer
          no-cache: true
          outputs: type=cacheonly
